/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuizzApp;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ButtonGroup;

/**
 *
 * @author jehow
 */
public class QuizGUI extends javax.swing.JFrame {
    ArrayList<question> quiz = new ArrayList<>();
    ButtonGroup options = new ButtonGroup();
    /**
     * Creates new form QuizGUI
     */
    public QuizGUI() {
        initComponents();
        
        options.add(rbA);
        options.add(rbB);
        options.add(rbC);
        options.add(rbD);
        QuizApp quiz1 = new QuizApp();
        quiz = quiz1.loadQuestions("quizQuestions.txt");
        
        Collections.shuffle(quiz);
        for(question q: quiz){
            System.out.println(q.question);
        }
        taQuestion.setText(quiz.get(0).getQuestion());  // Access the first question
        rbA.setText(quiz.get(0).getOption1());
        rbB.setText(quiz.get(0).getOption2());
        rbC.setText(quiz.get(0).getOption3());
        rbD.setText(quiz.get(0).getOption4());
    

    }
    
    public QuizGUI(String name) {
        initComponents();
        userName = name;
        options.add(rbA);
        options.add(rbB);
        options.add(rbC);
        options.add(rbD);
        QuizApp quiz1 = new QuizApp();
        quiz = quiz1.loadQuestions("quizQuestions.txt");
        
        Collections.shuffle(quiz);
        taQuestion.setText(quiz.get(0).getQuestion());  // Access the first question
        rbA.setText(quiz.get(0).getOption1());
        rbB.setText(quiz.get(0).getOption2());
        rbC.setText(quiz.get(0).getOption3());
        rbD.setText(quiz.get(0).getOption4());
    

    }
    String userName;
    static int quizLength = 15;
    int counter = 0;
    String userAnswer;
    String correctAnswer;
    int score[] = new int[15];
    int finalScore;
    public void display(){
        taQuestion.setText(quiz.get(counter).getQuestion());
        rbA.setText(quiz.get(counter).getOption1());
        rbB.setText(quiz.get(counter).getOption2());
        rbC.setText(quiz.get(counter).getOption3());
        rbD.setText(quiz.get(counter).getOption4());
        lblQuestionNum.setText("Question " + (counter+1) + " out of 15");
        
        userAnswer = quiz.get(counter).getUserAnswer();
        //System.out.println("thing fist" + userAnswer);
        if(quiz.get(counter).getOption1().equals(userAnswer)){
            rbA.setSelected(true);
        }else if(quiz.get(counter).getOption2().equals(userAnswer)){
            rbB.setSelected(true);
        }else if(quiz.get(counter).getOption3().equals(userAnswer)){
            rbC.setSelected(true);
        }else if(quiz.get(counter).getOption4().equals(userAnswer)){
            rbD.setSelected(true);
        }else{
            //System.out.println("stuff");
            /*rbA.setSelected(false);
            rbB.setSelected(false);
            rbC.setSelected(false);
            rbD.setSelected(false);*/
            options.clearSelection();
        }
        
    }
    public void finished(){
        if(correctAnswer.equals(userAnswer)){
                    score[counter] = 1;
                }else{
                    score[counter] = 0;
                }
            for (int i = 0; i < score.length; i++) {
                finalScore += score[i];
            }
            double percent = (double) finalScore / 15;
            percent = percent *100;
            try{
                PrintWriter out = new PrintWriter(new FileWriter("QuizScores.txt", true));

                out.print(userName);
                out.print(' ');
                out.println(percent);

                out.close();

            }catch(IOException ex){
                ex.printStackTrace();
            }
            QuizEndScreen q = new QuizEndScreen(percent, quiz);
            q.setVisible(true);
            this.dispose();
    }

    /*
    public String getUserAnswer(){
        if(rbA.isSelected()){
            userAnswer = quiz.get(counter).getOption1();
        }else if(rbB.isSelected()){
            userAnswer = quiz.get(counter).getOption2();
        }else if(rbC.isSelected()){
            userAnswer = quiz.get(counter).getOption3();
        }else if(rbD.isSelected()){
            userAnswer = quiz.get(counter).getOption4();
        }else{
            userAnswer = null;
        }
        return userAnswer;
    }*/
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Banner = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taQuestion = new javax.swing.JTextArea();
        rbA = new javax.swing.JRadioButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblQuestionNum = new javax.swing.JLabel();
        rbD = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        Banner.setBackground(new java.awt.Color(255, 255, 255));
        Banner.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Banner.setText("Quiz App");
        Banner.setOpaque(true);

        taQuestion.setColumns(20);
        taQuestion.setRows(5);
        jScrollPane1.setViewportView(taQuestion);

        rbA.setForeground(new java.awt.Color(255, 255, 255));
        rbA.setText("A");
        rbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAActionPerformed(evt);
            }
        });

        btnPrev.setText("Previous");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblQuestionNum.setBackground(new java.awt.Color(255, 255, 255));
        lblQuestionNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestionNum.setText("Question 1 out of 15");
        lblQuestionNum.setOpaque(true);

        rbD.setForeground(new java.awt.Color(255, 255, 255));
        rbD.setText("D");
        rbD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDActionPerformed(evt);
            }
        });

        rbB.setForeground(new java.awt.Color(255, 255, 255));
        rbB.setText("B");
        rbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBActionPerformed(evt);
            }
        });

        rbC.setForeground(new java.awt.Color(255, 255, 255));
        rbC.setText("C");
        rbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbD, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(btnSubmit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(rbB, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnPrev)
                        .addGap(26, 26, 26)
                        .addComponent(lblQuestionNum, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addGap(12, 12, 12)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbA)
                    .addComponent(rbB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbC)
                    .addComponent(rbD))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(lblQuestionNum))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        correctAnswer = quiz.get(counter).getCorrectAnswer();
            userAnswer = quiz.get(counter).getUserAnswer();
            //System.out.println(correctAnswer + "   " + userAnswer);
            if(correctAnswer.equals(userAnswer)){
                score[counter] = 1;
            }else{
                score[counter] = 0;
        }
        if(counter < 14){
            
            counter++;
            display();
        }else{
            finished();
            
        }
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        if(counter > 0){
            correctAnswer = quiz.get(counter).getCorrectAnswer();
            userAnswer = quiz.get(counter).getUserAnswer();
            if(correctAnswer.equals(userAnswer)){
                score[counter] = 1;
            }else{
                score[counter] = 0;
            }
            counter--;
            display();
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        finished();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void rbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBActionPerformed
        // TODO add your handling code here:
        String temp = quiz.get(counter).getOption2();
        quiz.get(counter).setUserAnswer(temp);
        //System.out.println(quiz.get(counter).getUserAnswer());
    }//GEN-LAST:event_rbBActionPerformed
//
    private void rbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAActionPerformed
        // TODO add your handling code here:
        String temp = quiz.get(counter).getOption1();
        quiz.get(counter).setUserAnswer(temp);
        //System.out.println(quiz.get(counter).getUserAnswer());
    }//GEN-LAST:event_rbAActionPerformed

    private void rbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCActionPerformed
        // TODO add your handling code here:
        String temp = quiz.get(counter).getOption3();
        quiz.get(counter).setUserAnswer(temp);
        //System.out.println(quiz.get(counter).getUserAnswer());
    }//GEN-LAST:event_rbCActionPerformed

    private void rbDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDActionPerformed
        // TODO add your handling code here:
        String temp = quiz.get(counter).getOption4();
        quiz.get(counter).setUserAnswer(temp);
        //System.out.println(quiz.get(counter).getUserAnswer());
    }//GEN-LAST:event_rbDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuestionNum;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbD;
    private javax.swing.JTextArea taQuestion;
    // End of variables declaration//GEN-END:variables
}
